### PR TITLE
feature/formfixes 

### PR DESCRIPTION
**Pull request by ZaneAugustyn**

### CODE REVIEW

**Comment by Keanumrc** [comment]
@ZaneAugustyn @GremBleen Any idea why so many files show changes (backend stuff, docs etc.) when they look pretty much identical?

**Review by Keanumrc — CHANGES_REQUESTED** [review]
Filters seem to no longer be working

**Comment by GremBleen** [comment]
> @ZaneAugustyn @GremBleen Any idea why so many files show changes (backend stuff, docs etc.) when they look pretty much identical?

Probably commit head changes, its caused by rebasing. It says that the commit hash has changed for the file but nothing in the file has been changed. Or it might be some minor formatting like a reduced indentation

**Comment by ZaneAugustyn** [comment]
Okay cool the chips now remove but the query json does not update so looking into it now

**Pull request merged**
