### PR TITLE
DatabaseConnectionModal basic frontend

### PR DESCRIPTION
**Pull request by Keanumrc**

### CODE REVIEW

**Comment by ZaneAugustyn** [comment]
Just check the text "Connect to a database" is not showing

**Comment by u22738917** [comment]
It appears that the modal header text is white, so we are unable to see it.

**Comment by XadrianvHeerden** [comment]
@Keanumrc please check to rebase your branch please then i can approve your pull request

**Comment by Keanumrc** [comment]
@XadrianvHeerden have done so

**Review by XadrianvHeerden — APPROVED** [review]

**Pull request merged**
