### PR TITLE
feat: routing and middleware working :)

### PR DESCRIPTION
**Pull request by u22738917**

### CODE REVIEW

**Review by Keanumrc — CHANGES_REQUESTED** [review]
@u22738917 Just make sure to remove the node_modules and other files outside of the app directory

**Comment by u22738917** [comment]
Hang on, I know I requested changes but for some reason the node module stuff is still there. Fixing now...

**Comment by u22738917** [comment]
Alright, should all be working now.

**Comment by Keanumrc** [comment]
I think also just remove the outer pnpm-lock.yaml since I see that it is also new. Thanks!

**Comment by u22738917** [comment]
Changes made

**Review by Keanumrc — APPROVED** [review]
Looks good!

**Pull request merged**
