### PR TITLE
Docs for Frotend (Please dont delete branch after merge)

### PR DESCRIPTION
**Pull request by XadrianvHeerden**

### CODE REVIEW

**Comment by XadrianvHeerden** [comment]
Please don't delete the branch after merge as I'm still working on it

**Comment by Keanumrc** [comment]
@XadrianvHeerden please add the docs for frontend technology choices

**Review by Keanumrc — CHANGES_REQUESTED** [review]
Just resolve the merge conflicts in the lock file and then I can merge

**Comment by XadrianvHeerden** [comment]
@Keanumrc  it should solved now I rebased the branch again

**Pull request merged**
